# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: fintecherp
services:
  gotenberg:
    image: gotenberg/gotenberg:8
    environment:
      - DISABLE_PROMETHEUS=1
    ports:
      - 127.0.0.1:3000:3000
